version: "3.9"

services:

  google-sheet-ocr:

    build: .
    container_name: google-sheet-ocr
    ports:
      - "8501:8501"

    volumes:
      - ./data:/app/data
      - ./temp:/app/temp

    restart: unless-stopped